### ISSUE TITLE
Spice of Life blue-screened server computer.

### ISSUE THREAD

**Issue by Emberion** [squeek502/SpiceOfLife#87] opened 2016-05-13 23:03 UTC
I have a lightly modded server that I was testing out earlier, but when I tried to join(server launched and was running without people fine) I crashed the server and got a fatal error message on my client. As the server computer blue screened, I don't have a crash log, but I do have some interesting log files(couldn't find this bit in any of my fml log files, so it's only partial). 

http://pastebin.com/nkHiEA9Z

**Comment by squeek502** [comment] 2016-05-14 00:45
Seems like a duplicate of https://github.com/squeek502/SpiceOfLife/issues/84. Still unsure what could be causing it.

**Closed as completed by squeek502** 2016-05-14 00:45 UTC
Labels: duplicate
