### ISSUE TITLE
[1.12.2]Tooltips will not be shown in JEI

### ISSUE THREAD

**Issue by SihenZhang** [squeek502/SpiceOfLife#157] opened 2018-12-17 13:59 UTC
Mod Version: 1.3.12
Forge Version: 14.23.5.2796
AppleCore Version: 3.1.4
JEI Version: 4.14.3.238
Description:
Tooltips will not be shown in JEI, but will be shown in the inventory normally.
Same issue in Spice of Life: Carrot Edition: https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/42
![](https://i.imgur.com/upVztpq.png)
![](https://i.imgur.com/KcEpFRK.png)

**Comment by squeek502** [comment] 2018-12-17 20:23
Caused by https://github.com/mezz/JustEnoughItems/pull/1388

Not sure how to resolve it, see [my comment there](https://github.com/mezz/JustEnoughItems/pull/1388#issuecomment-447984944).

**Comment by squeek502** [comment] 2019-01-16 00:16
Will be fixed after the next version of JEI: https://github.com/mezz/JustEnoughItems/commit/6f191f65f1f2b55a095cb336f87b7f9487bb463b

**Closed as completed by squeek502** 2019-01-16 00:16 UTC
Labels: bug
