### ISSUE TITLE
[req] Support rendering changes caused by Dual Hotbar

### ISSUE THREAD

**Issue by ghost** [squeek502/SpiceOfLife#18] opened 2014-08-13 01:40 UTC
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2178797-dual-hotbars?page=2

Dual Hotbar shifts the food bar up a bit, but the spice of life icons aren't moved as well: http://imgur.com/aqFX6Vu

**Comment by squeek502** [comment] 2014-08-13 03:27
Thanks for letting me know about this.

See: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2178797-dual-hotbars?comment=29

**Comment by squeek502** [comment] 2014-08-13 21:22
Tested and confirmed that the issue is on Dual Hotbar's end. It is fixed in the 1.6.4 version of Dual Hotbar but the fix didn't make it into the 1.7.10 version.

It should be fixed for all versions in the next Dual Hotbar release.

**Closed as completed by squeek502** 2014-08-13 21:22 UTC
