### ISSUE TITLE
Minecraft Freezes When Reentering World

### ISSUE THREAD

**Issue by charlie-e09ae35d** [squeek502/SpiceOfLife#84] opened 2016-03-25 13:09 UTC
multimc 0.4.11-703
minecraft 1.8.9
forge 11.15.1.1722

mod list:
applecore-mc1.8.9-1.3.0
spiceoflife-mc1.8.9-1.3.1

new multimc instance, default minecraft and mod settings,
using openjdk 64 bit 1.8.0_74, on linux amd64 4.4.5-1-arch

log: http://paste.ee/p/diWTC

most of the time when reentering newly generated world minecraft freezes requiring force close

**Comment by squeek502** [comment] 2016-03-25 18:27
Thanks for reporting. Not sure how that exception is possible, as it seems to be caused by the [EntityPlayer being `null` here](https://github.com/squeek502/SpiceOfLife/blob/1.8.9/java/squeek/spiceoflife/foodtracker/FoodHistory.java#L225), which means that `FMLClientHandler.instance().getClientPlayerEntity()` is returning `null`. Will try to reproduce it when I get a chance.

**Comment by nyanlathotep** [comment] 2016-04-12 20:29
I'm able to pretty reliably cause this exception by re-sizing the window while a single player world is loading, and I also get it unreliably just from loading a world without doing anything. Sometimes minecraft freezes and other times I get sent back to the main menu and then any further attempts to load the world on which it happened will fail the same way, returning me to the main menu. I have seen other worlds load fine after having that problem, though.
- Windows 8.1
- Java 1.8.0_25-b18
- Minecraft 1.8.9
- Forge 11.15.1.1794
- AppleCore 1.3.0
- Spice of Life 1.3.1

**Comment by squeek502** [comment] 2016-05-22 07:38
Should be fixed by https://github.com/squeek502/SpiceOfLife/commit/0339a45b8cd0c876fc97fae3182084a9c549ded5, will be fixed in the next version.

**Closed as completed by squeek502** 2016-05-22 07:38 UTC
Labels: bug
