### ISSUE TITLE
Crash when attempting to move open lunch box

### ISSUE THREAD

**Issue by Noobulus** [squeek502/SpiceOfLife#137] opened 2017-10-09 20:14 UTC
The game crashes when you attempt to move an open lunch box while the GUI is open. A safeguard against this, such as whatever TE uses for its sachels, would make the issue nonexistent.

**Comment by squeek502** [comment] 2017-10-10 11:02
This seems to be a regression in The Spice of Life for recent versions of MC (works fine in MC 1.10.2 and earlier). Will look more into it, thanks for reporting.

**Comment by squeek502** [comment] 2018-06-12 11:16
Should be fixed in 1.3.12

**Closed as completed by squeek502** 2018-06-12 11:16 UTC
Labels: bug
