### ISSUE TITLE
[1.10.2, v1.3.6] Texture missing for the food journal

### ISSUE THREAD

**Issue by turbosexophonic** [squeek502/SpiceOfLife#110] opened 2016-11-09 00:47 UTC
There is no texture in-game for the food journal, only the pink and black square to indicate a missing texture.  The console/log does not note its absence.

Minecraft Version: 1.10.2
Mod Version: 1.3.6

**Comment by squeek502** [comment] 2016-11-09 01:14
Duplicate of https://github.com/squeek502/SpiceOfLife/issues/100

**Closed as completed by squeek502** 2016-11-09 01:14 UTC
Labels: duplicate
